"""rename departmentss to department

Revision ID: 1e221b5b8fc6
Revises: cc953dbc69bc
Create Date: 2025-08-03 10:26:20.616364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e221b5b8fc6'
down_revision = 'cc953dbc69bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departmentss', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'departmentss')
    # ### end Alembic commands ###
