"""Add Department

Revision ID: cc2cb69f6895
Revises: 7f2495d6eb55
Create Date: 2025-08-02 13:15:49.748143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc2cb69f6895'
down_revision = '7f2495d6eb55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    op.alter_column('department', 'address', new_column_name='location')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
    op.alter_column('department', 'location', new_column_name='address')
