"""changed departments to departmentss"
;


Revision ID: cc953dbc69bc
Revises: cf45fbf0eaf6
Create Date: 2025-08-03 10:16:03.798147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc953dbc69bc'
down_revision = 'cf45fbf0eaf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.rename_table('departments', 'departmentss')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.rename_table('departmentss', 'departments')
    # ### end Alembic commands ###
