"""add department

Revision ID: cf45fbf0eaf6
Revises: ba39e2e6af31
Create Date: 2025-08-03 09:55:43.732090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf45fbf0eaf6'
down_revision = 'ba39e2e6af31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(), nullable=True))
        batch_op.drop_column('location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('address')

    # ### end Alembic commands ###
